/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define GPIOA_BASE 0X40010800
#define RCC_BASE 0X40021000
#define EXTI_BASE 0X40010400
#define AFIO_BASE 0X40010000
#define NVIC_BASE 0XE000E100
// Registers
#define APB2ENR *(volatile uint32_t*)(RCC_BASE+0x18)
//RCC Registers
#define CRL *(volatile uint32_t*)(GPIOA_BASE+0x00)
#define CRH *(volatile uint32_t*)(GPIOA_BASE+0x04)
#define ODR *(volatile uint32_t*)(GPIOA_BASE+0x0C)
// EXTI Registers
#define EXTI_IMR *(volatile uint32_t*)(EXTI_BASE+0x00)
#define EXTI_RISR *(volatile uint32_t*)(EXTI_BASE+0x08)
#define EXTI_PR *(volatile uint32_t*)(EXTI_BASE+0x14)
//AFIO Registers
#define AFIO_EXTICR1 *(volatile uint32_t*)(AFIO_BASE+0x08)
// NVIC registers
#define NVIC_ISER *(volatile uint32_t*)(NVIC_BASE+0x00)
void clock_init(void)
{
	//AFIO & GPIO clock enable
	APB2ENR |=(1<<0)|(1<<2);
}
void GPIOA_init(void)
{  // configure PA0 as input floating point
	CRL |=(1<<2);
	//configure PA13 as general purpose output 2 MHZ
	CRH &=0xFF0FFFFF;
	CRH |=0x00200000;
}
void EXTI_init(void)
{   // mapping PA0 to EXTI0
	AFIO_EXTICR1 =0x0;
	// rising edge mode
	EXTI_RISR |=(1<<0);
	// mask EXTI0
	EXTI_IMR |=(1<<0);
	// enable EXTI0 that has index 6 according to IVT in NVIC inside cortex-m3 TRM
	NVIC_ISER |=(1<<6);
}
int main(void)
{
	clock_init();
	GPIOA_init();
	EXTI_init();
	while(1);

}
void EXTI0_IRQHandler(void)
{  // toggle led on PA13
	ODR	^= (1<<13);
	// clear pending interrupt bit by write 1
	EXTI_PR |= (1<<0);
}
